name: dev-workflow

on:
  - push
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest
          # - windows-latest
        go:
          - '1.19'
          # - '1.18'
          # - '1.17'
          # - '1.16'
          # - '1.15'
    env:
      OS: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@master

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.48

    - name: Test
      run: make test

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
